# Config file for automatic testing at travis-ci.org
language: python

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set auto_update_conda no
  - conda update -q conda

install:
  - conda install python numpy pandas matplotlib scipy ezc3d -c mrtnz
  - conda install conda-build anaconda-client pytest pytest-cov
  - conda build conda.recipe --no-test -c mrtnz
  - conda install --use-local pyomeca
  - conda info -a

script:
  - pytest -v --color=yes --cov=pyomeca tests

after_success:
  - conda install -c conda-forge codecov
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always