language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install conda-build
  - git clone git@github.com:pyomeca/conda_recipes.git

install:
  - conda env create -f env.yml
  - source activate pyomeca

  - conda build conda_recipes/pyomeca
  - conda install pyomeca --use-local

script:
  - python -m pytest --cov=pyomeca tests/

notifications:
  email:
    on_success: never
    on_failure: always