# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: pyomeca
channels:
- defaults
- pyomeca
- conda-forge
dependencies:
- python
- numpy
- pandas
- matplotlib
- scipy
- ezc3d
- pytest
- pytest-cov
